config/routes.rb
Rails.application.routes.draw do
  root 'accesslogs#index'
  get 'accesslogs/token_create'
  post 'accesslogs/create'
end

app/models/access_log.rb
class AccessLog < ApplicationRecord
  belongs_to :token
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/token.rb
class Token < ApplicationRecord
  has_many :access_logs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accesslogs_controller.rb
class AccesslogsController < ApplicationController
  protect_from_forgery except: :create

  def index
    @access_log_array = []
    @access_logs_urls = []
    return unless params.has_key?(:settings)
    token = params[:settings][:token]
    url = params[:settings][:url]
    @date = params[:settings][:date]
    @token = Token.find_by(identifier: token)
    @accesslogs = @token.access_logs

    24.times do |hour|
      begin_time = Time.zone.parse("#{@date} #{hour}:00")
      end_time = Time.zone.parse("#{@date} #{hour}:59")

      if url.present?
        @access_log_array << @accesslogs.where(created_at: begin_time..end_time, url: url).count
        @url = url
      else
        @access_log_array << @accesslogs.where(created_at: begin_time..end_time).count
        @url = "WEBサイト全体"
      end
    end

    @sum_access_log_count = 0
    @access_log_array.each do |count|
      @sum_access_log_count += count
    end

    @accesslogs.each do |access_log|
      @access_logs_urls << [access_log.url, access_log.url]
    end
  end

  def token_create
    @access_log_array = []
    @access_logs_urls = []

    token = Token.new
    random = SecureRandom.uuid
    token.identifier = random
    token.save
    @tag = "<script id=\"data\" data-token=\"#{token.identifier}\" async src=\"http://localhost:3000/pv_analytics.js\"></script>"
    render :index
  end

  def create
    response.headers["Access-Control-Allow-Origin"] = "*"
    response.headers["Access-Control-Allow-Methods"] = "POST"
    response.headers["Access-Control-Allow-Headers"] = "Content-Type"
    token = Token.find_by(identifier: params[:token])
    token.access_logs.create(url: params[:url])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/accesslogs_helper.rb
module AccesslogsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accesslogs/index.html.erb
<h1>PvAnalytics</h1>
<div class="contents_container">
  <div class="tag_create">
    <h3>タグ発行</h3>
    <%= text_area_tag(:tag, @tag, class: 'tag_create_area') %>
    <div>
     <%= link_to accesslogs_token_create_path do %>
      <%= button_tag "タグ発行", class: 'btn btn-primary tag_button' %>
     <% end %>
    </div>
  </div>
  <div class="data_aggregation">
    <h2>集計結果</h2>
    <div class="aggregation_table">
      <table border>
        <tr>
          <th>時間帯</th>
          <th>pv</th>
        </tr>
        <%- @access_log_array.each_with_index do |pv, index| %>
        <tr>
          <td><%= index %>:00 ~ <%= index %>:59</td>
          <td class= "pvtd"><%= pv %></td>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
  <%= form_tag(root_path, method: :get) do %>
  <div class="function">
    <label>Date:</label>
    <div>
      <%= text_field(:settings, :date, required: true, class: 'form', :placeholder => "2018/09/20") %>
    </div>
    <div class="token_url_boxcontainer">
      <div class="token">
        <%= label_tag(:token, 'Token:') %>
        <div>
          <%= text_field(:settings, :token, required: true, class: 'token_form', :placeholder => "data-token=\"ここに記載されているtokenを貼り付けてください。\"") %>
        </div>
      </div>
      <div class="url">
        <label>url:</label>
          <div class = 'form'>
            <%= select_tag 'settings[url]', options_for_select(@access_logs_urls.uniq), include_blank: true %>
          </div>
      </div>
    </div>
    <%= submit_tag('集計を見る', class: 'btn btn-primary') %>
    <div class="sumtable">
      <table border class="sumtable">
          <tr>
            <th>日付</th>
            <th>WEBサイト全体 or URL</th>
            <th>総PV数</th>
          </tr>
          <tr>
            <td><%= @date %></td>
            <td><%= @url %></td>
            <td><%= @sum_access_log_count %></td>
          </tr>
      </table>
    </div>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PvAnalytics</title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>